### ISSUE TITLE
comunication across unity and react

### ISSUE THREAD

**Issue by mariuschiriac** [KurtGokhan/react-unity#3]
Hi,
Is there a way to pass data from the ui generated by react and unity game?
i.e. changing the move speed of a gameobject when clicking a button.

**Comment by KurtGokhan** [comment]
Right now the easiest way is to use `NamedAssets`. Added an example here:

https://github.com/KurtGokhan/react-unity-full-sample/blob/master/react/src/interop/index.tsx

You can see this example in action by going to Scenes/Interop

![Imgur](https://i.imgur.com/ZqYLjRu.gif)

**Comment by KurtGokhan** [comment]
Added [wiki page](https://github.com/KurtGokhan/react-unity/wiki/Communication-between-Unity-and-React) with same info.
