### ISSUE TITLE
create custom component

### ISSUE THREAD

**Issue by mariuschiriac** [KurtGokhan/react-unity#4]
how can i create a custom markdown high-level components and integrate it into react-unity and assign to it a custom style 
IE: images, gradient...

**Comment by KurtGokhan** [comment]
Available in 0.0.4. Added a [wiki page](https://github.com/KurtGokhan/react-unity/wiki/Custom-Primitive-Components) for this.

In the future, I will add more explanation for how to use components in layout measurements. For now, these things can be learned by inspecting the source code of leaf components, like `TextComponent` or `ImageComponent`. Anyway, it is too early for this project to add such detailed documentation.
