### ISSUE TITLE
Can't build for iOS

### ISSUE THREAD

**Issue by joukosaastamoinen** [KurtGokhan/react-unity#5]
This is an awesome project!

I was trying to build a Unity project using `react-unity` for iOS, but the build failed in Xcode with these errors:

![image](https://user-images.githubusercontent.com/3137755/84594776-399cf280-ae5d-11ea-8490-4b595ab84270.png)

Does `react-unity` (yet) support iOS?

Unity version: 2019.4.0f1

**Comment by KurtGokhan** [comment]
I noticed that I did not include Yoga native library for iOS. I don't own a Mac so I can't build Yoga for iOS. You may try the prebuilt library file I found here: https://github.com/justinsuen/shiparoo-ios/blob/master/ios/build/Build/Products/Debug-iphonesimulator/libyoga.a

Basically, put this file in the `Plugins/iOS` folder of your project and set the configuration in Unity like this https://monosnap.com/file/on4Td3UqHHCYeWpWDdCN2Li1jibGVs

Let me know if this works for you so I can include it in `react-unity`.

**Comment by KurtGokhan** [comment]
I created a possible fix for this issue in `iosbuild` branch. @joukosaastamoinen Please try updating your manifest.json file to point to this branch like:

```
"com.kurtgokhan.react-unity": "https://github.com/KurtGokhan/react-unity.git#iosbuild"
```

**Comment by joukosaastamoinen** [comment]
> I created a possible fix for this issue in `iosbuild` branch. @joukosaastamoinen Please try updating your manifest.json file to point to this branch like:
> 
> ```
> "com.kurtgokhan.react-unity": "https://github.com/KurtGokhan/react-unity.git#iosbuild"
> ```

This worked! Thank you a lot!

**Comment by KurtGokhan** [comment]
Thanks for testing! I am glad it works for you.

**Comment by KurtGokhan** [comment]
Closing as fixed.
