### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by favoyang** [KurtGokhan/react-unity#6]
Git tag: [v0.0.5](https://github.com/KurtGokhan/react-unity/tree/v0.0.5)
package.json version: 0.0.4

To fix: bump version then re-tag v0.05

Further reading:
- Managing release with CI: https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c
- Managing release with CLI https://medium.com/openupm/how-to-maintain-upm-package-part-4-managing-package-release-with-cli-972ff5311163

**Comment by KurtGokhan** [comment]
Thanks. I was wondering why I got that error. 

Also these blog posts are very helpful.
